### ISSUE TITLE
Please add support for folder view in Visual Studio 2017

### ISSUE THREAD

**Issue by alexangas** [madskristensen/ImageOptimizer#35]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 3.6.103

### Description
Right now to optimize several images I have to create a solution and project, add the images, and then run the optimizer.

Can you please add support for folder view so there is no need for a solution file?

**Comment by webluke** [comment]
I had to do a full reinstall of VS2017 to get this installed, but I wish I had seen this post sooner because that is what I was trying to do. Just wanted to File > Open > Folder and right click on any image or image folder and have it optimise like described in the description. Too bad it's set to specific project types or not just a global tool.
